
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Stack;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class Analizador extends javax.swing.JFrame {
public ArrayList<Lista> cuadruplos=new ArrayList();
Iterator<Lista> iter = cuadruplos.iterator();
public Stack <Integer> pE=new Stack <>();
public Stack  poperadores =new Stack ();
public Stack  numeros =new Stack ();
public Stack  poperandos =new Stack ();
public Stack  poperandoscompara =new Stack (),poperanco2 = new Stack();
public Stack  tiposcompara =new Stack ();
public Stack  psaltos =new Stack ();
public Stack  tipos =new Stack ();
String tip="",operando="",operadores="",tipo="",op1="",op2="",oper="",res="",tipoq="",operando1="",saltos="",resTipo="";
String err="",peek="";
int num=1,tipo1=0,sd=0;
int indice=1; 
int salto;
Lista obj=new Lista();
String [] variable;
boolean plus=false,resta=false,multi=false,divi=false,igual=false,men=false,may=false,WHILE=false,wh=false,
        meni=false,mayi=false,difde=false,If=false,forr=false,whilee=false,elsee=false,endif=false,
        Endw=false,whil=false,com=false,cons=false, ig=false,opt=false,cons1=false,endw=false,enf=false,elseie=false,whi=false,io=false;
  int resu,nubo,nobo1;
  String re="",sal="",oper1,oper2,oper3,oper4;
  Map<String, String> map = new HashMap<>();

                                //OP1 OP2 +-*  /  d.m rec and nor or
static int [][] matrizDeTipos  ={{138,138,138,139,138,142,544},
                                 {138,139,139,139,544,142,544},
                                 {138,140,544,544,544,544,544},
                                 {138,141,544,544,544,544,544},
                                 {138,142,544,544,544,544,544},
                                 {139,138,139,139,544,142,544},
                                 {139,139,139,139,544,142,544},
                                 {139,140,544,544,544,544,544},
                                 {139,141,544,544,544,544,544},
                                 {139,142,544,544,544,544,544},
                                 {140,138,544,544,544,544,544},
                                 {140,139,544,544,544,544,544},
                                 {140,140,544,544,544,142,544},
                                 {140,141,544,544,544,544,544},
                                 {140,142,544,544,544,544,544},
                                 {141,138,544,544,544,544,544},
                                 {141,139,544,544,544,544,544},
                                 {141,140,544,544,544,142,544},
                                 {141,141,544,544,544,142,544},
                                 {141,142,544,544,544,544,544},
                                 {142,138,544,544,544,544,544},
                                 {142,139,544,544,544,544,544},
                                 {142,140,544,544,544,544,544},
                                 {142,141,544,544,544,544,544},
                                 {142,142,544,544,544,142,142}};
String[] columnNames = {"#", "OPER", "OP1", "OP2", "RES"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    /**
     * Creates new form Analizador
     */
    public Analizador() {
        initComponents();
        tabla.setModel(model);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtsaltos = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txterr = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txttipos = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtoperadores = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtoperandos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta1 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(txta);

        jScrollPane4.setViewportView(txtsaltos);

        jButton1.setText("Analizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(txterr);

        txttipos.setColumns(20);
        txttipos.setRows(5);
        jScrollPane9.setViewportView(txttipos);

        txtoperadores.setColumns(20);
        txtoperadores.setRows(5);
        jScrollPane10.setViewportView(txtoperadores);

        txtoperandos.setColumns(20);
        txtoperandos.setRows(5);
        jScrollPane11.setViewportView(txtoperandos);

        jLabel1.setText("Entrada");

        jLabel3.setText("Errores");

        jLabel4.setText("Tipos");

        jLabel5.setText("operandos");

        jLabel6.setText("Operadores");

        jLabel7.setText("Saltos");

        jScrollPane1.setViewportView(tabla);

        jScrollPane3.setViewportView(txta1);

        jLabel8.setText("Salida");

        jLabel9.setText("optimizacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7))
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    int reservadas(String reservada)
{
    
   

   
     switch (reservada)
            {
                case "import":
                    return 1;
                case "class":
                    return 2;
                case "begin":
                    return 3;
                case "end":
                    return 4;
                case "def":
                    return 5;
                case "as":
                    return 6;
                case "integer":
                    return 7;
                case "float":
                    return 8;
                case "char":
                    return 9;
                case "string":
                    return 10;
                case "boolean":
                    return 11;
                case "if":
                    return 12;
                case "endif":
                    return 13;
                case "else":
                    return 14;
                case "endwhile":
                    return 15;
                case "while":
                    return 16;
                case "endfor":
                    return 17;
                case "for":
                    return 18;
                case "enter":
                    return 19;
                case "write":
                    return 20;
                case "read":
                    return 21;
                case "principal":
                    return 22;
                case "elseif":
                    return 23;
                case "function":
                    return 24;
                case "endfunction":
                    return 25;
                case "null":
                    return 26;
                case "include":
                    return 27;
                case "+":
                    return 28;
                case "-":
                    return 29;
                case "*":
                    return 30;
                case "/":
                    return 31;
                case "=":
                    return 32;
                case ",":
                    return 33;
                case ";":
                    return 34;
                case "<":
                    return 35;
                case ">":
                    return 36;
                case ">=":
                    return 37;
                case "<=":
                    return 38;
                case "!=":
                    return 39;
                case "(":
                    return 40;
                case ")":
                    return 41;
                case ":":
                    return 42;
                case "1":return 43;case "2":return 43;case "3":return 43;case "4":return 43;case "5":return 43;
                case "10":return 43;case "9":return 43;case "8":return 43;case "7":return 43;case "6":return 43;case "0":return 43;
                
                
                
            }
        return 0;
}
void comparatipos(String a, String b, String o) {
        /*
    e=1
    f=2
    c=3
    s=4
         */
        
	//ERRORES
	
        if ("integer".equals(a) && "integer".equals(b) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("integer".equals(a) && "float".equals(b) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("integer".equals(a) && "char".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("integer".equals(a) && "string".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("integer".equals(a) && "boolean".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("float".equals(a) && "integer".equals(b) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("float".equals(a) && "float".equals(b) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("float".equals(a) && "char".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("float".equals(a) && "string".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("float".equals(a) && "boolean".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("char".equals(a) && "integer".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("char".equals(a) && "float".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("char".equals(a) && "char".equals(b) && ("*".equals(o) || "+".equals(o)) || ("-".equals(o) || "/".equals(o)) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("char".equals(a) && "string".equals(b) && ("*".equals(o) || "+".equals(o)) || ("-".equals(o) || "/".equals(o)) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("char".equals(a) && "boolean".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("string" == a && "integer" == b) {
            err += "Error entre tipos \n";

        }
        if ("string".equals(a) && "flotante".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("string".equals(a) && "char".equals(b) && ("*".equals(o) || "+".equals(o)) || ("-".equals(o) || "/".equals(o)) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("string".equals(a) && "string".equals(b) && ("*".equals(o) || "+".equals(o)) || ("-".equals(o) || "/".equals(o)) && ("mod".equals(o)) && ("AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            err += "Error entre tipos \n";
        }
        if ("string".equals(a) && "boolean".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("boolean".equals(a) && "integer".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("boolean".equals(a) && "flotante".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("boolean".equals(a) && "char".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("boolean".equals(a) && "string".equals(b)) {
            err += "Error entre tipos \n";
        }
        if ("boolean".equals(a) && "boolean".equals(b) && ("*".equals(o) || "+".equals(o)) || ("-".equals(o) || "/".equals(o)) && ("mod".equals(o))) {
            err += "Error entre tipos \n";
        }

	//Tipos de resultado

	//Integer
	
	if ("integer".equals(a) && "integer".equals(b) && ("*".equals(o) || "+".equals(o) || "-".equals(o) || "mod".equals(o))) {
            
	resTipo = "integer";

        }
	
	if ("integer".equals(a) && "integer".equals(b) && "/".equals(o)) {
            
	resTipo = "float";

        }

	if ("integer".equals(a) && "integer".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }

	if ("integer".equals(a) && "float".equals(b) && ("*".equals(o) || "+".equals(o) || "-".equals(o) || "/".equals(o))) {
            
	resTipo = "float";

        }
	
	if ("integer".equals(a) && "float".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	//Float
	if ("float".equals(a) && "integer".equals(b) && ("*".equals(o) || "+".equals(o) || "-".equals(o) || "/".equals(o))) {
            
	resTipo = "float";

        }
	
	if ("float".equals(a) && "integer".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	//Char
	if ("char".equals(a) && "char".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	if ("char".equals(a) && "string".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	//String
	if ("string".equals(a) && "char".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	if ("string".equals(a) && "string".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o))) {
            
	resTipo = "boolean";

        }
	
	//Boolean
	if ("boolean".equals(a) && "boolean".equals(b) && ("==".equals(o) || "<".equals(o) || ">".equals(o) || "<=".equals(o) || ">=".equals(o) || "AND".equals(o) || "NOR".equals(o) || "OR".equals(o))) {
            
	resTipo = "boolean";

        }

    }
void asignatipos(String a,String b, String o)
{
   
    if ("integer".equals(a) && "integer".equals(b) && "=".equals(o)) {
            resTipo = "integer";
        }
    else if ("integer".equals(a) && "float".equals(b) && "=".equals(o)) {
            resTipo = "float";
        }
    else if ("string".equals(a) && "string".equals(b) && "=".equals(o)) {
            resTipo = "string";
        }
    else if ("string".equals(a) && "char".equals(b) && "=".equals(o)) {
            resTipo = "string";
        }
    else if ("char".equals(a) && "char".equals(b) && "=".equals(o)) {
            resTipo = "char";
        }
    else if ("float".equals(a) && "float".equals(b) && "=".equals(o)) {
            resTipo = "float";
        }
    else if ("float".equals(a) && "integer".equals(b) && "=".equals(o)) {
            resTipo = "float";
        }
    else if ("boolean".equals(a) && "boolean".equals(b) && "=".equals(o)) {
            resTipo = "boolean";
        }
    else
    {
        err+="Error";
    }
}
    void cuadruplos(int a)
    {
        
        
        
       switch(a)
       {
           case 1:
            if(endw==false && elseie==false){ // condicoin para respetar la ejecucion logica
            op2=(String) poperandos.pop();
            int tipo1=poperanco2.search(op2);
            if(tipo1==-1)
            {
                
                poperanco2.push(op2);
                
                tiposcompara.push("integer");
                
            }
            tipo1=poperanco2.search(op2);
            
            
            String compartip=(String) tiposcompara.elementAt(tipo1-1);
            imprimepilaop2();
            tipos.pop();
            imprimepilatipos();
            op1=(String) poperandos.pop();
            imprimepilaop2();
            int tipo2=poperanco2.search(op1);
            String compartip1=(String) tiposcompara.elementAt(tipo2-1);
            res="r"+indice;
            tipos.pop();
            imprimepilatipos();
            oper=(String) poperadores.pop();
            imprimepilaoperadores();
            comparatipos(compartip, compartip1, oper);
            imprimepilaoperadores();
            if("<".equals(oper) || ">".equals(oper)) // detectar las comparaciones para determinar si es una condicoin
            {
                if((!"1".equals(op1) || !"2".equals(op1) || !"3".equals(op1) || !"4".equals(op1) || !"5".equals(op1)) && (!"1".equals(op2) ||
           !"2".equals(op2) || !"3".equals(op2) || !"4".equals(op2) || !"5".equals(op2)) ){
                try{
                int p = Integer.parseInt(map.get(op1)); // se obitiene el valor de las variables para determinar v o f
                int q=Integer.parseInt(map.get(op2));
                
                if ("<".equals(oper))
                {
                    oper1=op1;
                    oper2=op2;
                    if(p<q){
                    res="True";
                    endw=false;
                    enf=true;
                    }
                    else
                    {
                    res="False";
                    endw=true;
                    enf=false;
                 
                    }
                }
                if (">".equals(oper))
                {
                    oper1=op1;
                    oper2=op2;
                    if(p>q){
                    res="True";
                    endw=false;
                    enf=true;}
                    else{
                    if(whi==true)
                    {
                    }
                    else{
                    res="False";
                    endw=true;
                    enf=false;
                    }}
                }
                }
                catch(Exception e)
                {
                    
                }
            }
            }
            if("+".equals(oper) || "-".equals(oper))
            {
                // identificar suma o resta para aplicarla directo a los cuadruplos
                System.out.println(op1+" "+op2);
                
                if( ("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1) || "6".equals(op1))&&
                        (("1".equals(op2) || "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2) || "6".equals(op2))))
                {
                    cons=true;
                }
                if(cons==false){
                try{
                System.out.println("JJ"+cons);
                int p =Integer.parseInt(map.get(op1));
                int q=Integer.parseInt(map.get(op2));
                if ("+".equals(oper))
                {
                  res=String.valueOf(p+q);
                  map.put("op1", ""+p);
                  map.put("op2", ""+q);
                }
                else if("-".equals(oper)){
                res=String.valueOf(p-q);
                }
                }
                catch(Exception e)
                {
                    System.out.println("cart");
                    int p =Integer.parseInt(map.get(op1));
                    int q=Integer.parseInt(op2);
                    
                    if ("+".equals(oper))
                {
                    oper3=map.get(op1);
                    oper4=op2;
                  res=String.valueOf(p+q);
                  map.put("op1", ""+p);
                  map.put("op2", ""+q);
                }
                else if("-".equals(oper)){
                res=String.valueOf(p-q);
                }
                }}
                }
           if(("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1)) && ("1".equals(op2) ||
           "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2)) )
           {
               // si es una suma de constantes se hace la optimizacion de cuadruplos para que se asigne directamnete
               optimiza(num,oper,op1,op2,res);
               //num--;
           }
           else if(cons==false && (res!="True" && res!="False"))
           {
               JOptionPane.showMessageDialog(null, "cont ggg");
               JOptionPane.showMessageDialog(null, op1+op2);
               optimiza(num,oper,map.get(op1),map.get(op2),res);
           }
           else
           {
          
              model.addRow(new Object[]{num,oper,op1,op2,res});
           }
           
            obj.n=Integer.toString(num);
            obj.oper=oper;
            obj.op1=op1;
            obj.op2=op2;
            obj.res=res;
            cuadruplos.add(obj);
            poperandos.push(res);
            tipos.push(resTipo);
            imprimepilatipos();
            imprimepilaop2();
            indice++;
            num++;
            }
            break;
            
            case 2://ASIGNA
            if(endw==false){
            op2=null;
            res=(String) poperandos.pop();
            tipos.pop();
            imprimepilatipos();
            imprimepilaop2();
            op1=(String) poperandos.pop();
            tipos.pop();
            imprimepilatipos();
            imprimepilaop2();
            oper=(String) poperadores.pop();
            imprimepilaoperadores();
            if(opt==false){
                
                model.addRow(new Object[]{num,oper,op1,op2,res});
                map.put(op1, res);
                map.put(op1+"1", res);
                
            }
            else{
                
                optimiza(num,oper,op1,op2,res); // manda para poder asignar constantes a variables
                num--;
            }
            obj.n=Integer.toString(num);
            obj.oper=oper;
            obj.op1=op1;
            obj.op2=op2;
            obj.res=res;
            cuadruplos.add(obj);
            
            imprimepilatipos();
           
            num++;}
            break;
            //Acciones IF
            case 3:
                if(endw==false || ig== true){
                op2=null;
                op1=(String) poperandos.pop();
                tipos.pop();
                imprimepilaop2();
                res=null;
                oper="SF";
                model.addRow(new Object[]{num,oper,op1,op2,res});
                obj.n=Integer.toString(num);
                obj.oper=oper;
                obj.op1=op1;
                obj.op2=op2;
                obj.res=res;
                cuadruplos.add(obj);
                psaltos.push(num);
                imprimepilasaltos();
                num++;}
            break;
            case 4:
                if(endw==false || ig==true){
                op2=null;
                op1=null;
                res=null;
                oper="SI";
                salto=(int) psaltos.pop();
                imprimepilasaltos();
                model.setValueAt(num+1, salto-1, 4);
                model.addRow(new Object[]{num,oper,op1,op2,res});
                obj.n=Integer.toString(num);
                obj.oper=oper;
                obj.op1=op1;
                obj.op2=op2;
                obj.res=res;
                cuadruplos.add(obj);
                psaltos.push(num);
                imprimepilasaltos();
                num++;}
                break;
            case 5:
                if(endw==false ){
                poperadores.pop();
                imprimepilaoperadores();
                salto=(int) psaltos.pop();
                imprimepilasaltos();
                model.setValueAt(num, salto-1, 4);}
                break;
                //Acciones While
            case 6:
                if(endw==false || ig==true ){
                op2=null;
                op1=null;
                oper="SI";
                salto=(int) psaltos.pop();
                imprimepilasaltos();
                model.setValueAt(num+1, salto-1, 4);
                model.addRow(new Object[]{num,oper,op1,op2,salto-1});
                obj.n=Integer.toString(num);
                obj.oper=oper;
                obj.op1=op1;
                obj.op2=op2;
                obj.res=res;
                cuadruplos.add(obj);
                nobo1=num-1;}
                num++;
                break;
            case 7:
                if(endw==false){
                op2=null;
                op1=(String) poperandos.pop();
                tipos.pop();
                imprimepilatipos();
                imprimepilaop2();
                res=null;
                oper="SV";
                model.addRow(new Object[]{num,oper,op1,op2,res});
                obj.n=Integer.toString(num);
                obj.oper=oper;
                obj.op1=op1;
                obj.op2=op2;
                obj.res=res;
                cuadruplos.add(obj);
                psaltos.push(num);
                imprimepilasaltos();
                num++;}
            break;
            case 8:
                if(endw==false){
            op2=null;
            res=(String) poperandos.pop();
            tipos.pop();
            imprimepilatipos();
            imprimepilaop2();
            op1=(String) poperandos.pop();
            tipos.pop();
            imprimepilatipos();
            imprimepilaop2();
            oper=(String) poperadores.pop();
            imprimepilaoperadores();
            model.addRow(new Object[]{num,oper,op1,op2,res});
                obj.n=Integer.toString(num);
                obj.oper=oper;
                obj.op1=op1;
                obj.op2=op2;
                obj.res=res;
                cuadruplos.add(obj);
                imprimepilatipos();
            
            num++;}
            break;
            
            case 9: // para imprimir los write
                if(endw==false){
            op1="";
            op2="";
            oper="write";
            res=(String) poperandos.pop();
            model.addRow(new Object[]{num,oper,op1,op2,res});
            
            int q=Integer.parseInt(map.get("B1")),p=Integer.parseInt(map.get("A1"));
            
            
                
            if(map.get(res)==null)
            {
                sal+= " -> : " +  res+ "\n";
                map.put(""+sd++, res);
                numeros.push(sd);
                txta1.setText(sal);
            
            
            
            }
            else{
            
            sal+= " -> : " +  map.get(res)+ "\n";
            map.put(""+sd++, map.get(res).toString());
            numeros.push(sd);
            txta1.setText(sal);
            
            }
            
            
            num++;
                }
                
            break;    
                
                
       }    
    }
 void optimiza(int num,String oper,String op1,String op2,String ress) // resive todos los argumentos de los cuadruplos para optimizar operaciones
 {
   
if("+".equals(oper) && ("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1)) && ("1".equals(op2) ||
           "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2)) )
{
    
    int a=Integer.parseInt(op1);
    int b=Integer.parseInt(op2);
    map.put("op1", ""+a); // se inserta en un hashmap el valor y la constante(clave-valor) para poder validar la ejecucion del while
    map.put("op2", ""+b);
    resu = a+b;
    re=Integer.toString(resu);
    System.out.println(""+re);
    opt=true;
}
if("-".equals(oper) && ("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1)) && ("1".equals(op2) ||
           "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2)) )
{
    
    int a=Integer.parseInt(op1);
    int b=Integer.parseInt(op2);
    resu = a-b;
    re=Integer.toString(resu);
    System.out.println(""+re);
    opt=true;
}
if("*".equals(oper) && ("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1)) && ("1".equals(op2) ||
           "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2)) )
{
    
    int a=Integer.parseInt(op1);
    int b=Integer.parseInt(op2);
    resu = a*b;
    re=Integer.toString(resu);
    System.out.println(""+re);
    opt=true;
}
if("/".equals(oper) && ("1".equals(op1) || "2".equals(op1) || "3".equals(op1) || "4".equals(op1) || "5".equals(op1)) && ("1".equals(op2) ||
           "2".equals(op2) || "3".equals(op2) || "4".equals(op2) || "5".equals(op2)) )
{
    
    int a=Integer.parseInt(op1);
    int b=Integer.parseInt(op2);
    resu = (a/b);
    re=Integer.toString(resu);
    System.out.println(""+re);
    opt=true;
}

if("=".equals(oper))
{
    
    model.addRow(new Object[]{num-1,oper,op1,"",re}); // se hace la optimizacion de las asignaciones 
    map.put(op1, re);
    opt=false;
}

 }      
void analiza()
{
    boolean def=false,iden=false,pcom=false;
    int cont=0;
    int contc=1;
    int cont2=0;
    int edo=0;
    String texto="";
    String string = txta.getText();
    StringTokenizer st =new StringTokenizer(string);
    String cadena2=txta.getText();
   
while(st.hasMoreElements()) 
{
    String token = st.nextElement().toString();
    int reser=reservadas(token);

    if(reser==5 || def==true)
            {
               
               def=true;
                 if(reser==0 || iden==true)
                 {
                     
                     iden=true;

                    if(reser==0){
                         boolean a=poperandos.contains(token);
                        if(a==true)
                        {
                            err+="Error Variable "+token+" ya inicializada \n";
                            
                        }
                        else
                        {
                            poperandos.push(token);
                            poperandoscompara.push(token);
                            imprimepilaop2();
                            cont++;
                            
                        }

                    }
                    
                    if(reser==7)//INTEGER
                    {
                       
                        
                        for(int i=0;i<cont;i++)
                        {
                            tipos.push("integer");
                            tiposcompara.push("integer");
                            imprimepilatipos();
                            
                        }

                    cont=0;
                    }
                    if(reser==8)
                    {
                        for(int i=0;i<cont;i++)
                        {
                            tipos.push("float");
                            tiposcompara.push("float");
                            imprimepilatipos();
                           
                        }
                     cont=0;

                    }
                    if(reser==9)
                    {
                        for(int i=0;i<cont;i++)//char
                        {
                            tipos.push("char");
                            tiposcompara.push("char");
                            imprimepilatipos();
                        }

                    cont=0;
                    }
                    if(reser==10)
                    {
                        for(int i=0;i<cont;i++)
                        {
                            tipos.push("string");
                            tiposcompara.push("string");
                            imprimepilatipos();
                        }
                      cont=0;

                    }
                    if(reser==11)
                    {
                        for(int i=0;i<cont;i++)
                        {
                            tipos.push("boolean");
                            tiposcompara.push("bolean");
                            imprimepilatipos();
                        }

                        cont=0;
                    }
                    

                 }

            }
    
    if (reser==43)
        {
            cons1=true;
        }
    if(reser==34 || pcom==true)
    {
        if(reser==34)
        {
            if(!poperadores.empty())
            peek=(String) poperadores.peek();
            if("=".equals(peek))
            {
                cuadruplos(2);
            }
            
        }
        if(reser==5 || def==true)
        {
            def=true;
            if(reser==34)
            {def=false;
            pcom=true;
            if (reser==34){
        limpiapilaoperandos(); // se vacian las pilas de tipo y de operandos despues de definir las variables
        limpiapilatipos2();
        }}
        }
        else{
           
        
        def=false;
         if(reser==20)//:
            {
                whil=true;
                System.out.println("whil true");
                
            }
        if(reser==12)//if
            {
                ig=true;
                If=true;
                poperadores.push("$");
                imprimepilaoperadores();//$ utilizado como fondo falso del if
            }
        if(reser==14)//else
            {
            if(enf==true)
            {elseie=true;}
            else
            {endw=false;
                elseie=false;}
                
                elsee=true;
                //cuadruplos(4);
            }
        if(reser==13)//endif
            {
            elseie=false;
            igual=false;
            endw=false;
                endif=true;
                cuadruplos(5);
            }
        if(reser==16)//while
            {
                wh=true;
                WHILE=true;
                psaltos.push(num);
                
            }
        if(reser==15)//ENDwhile
            {
            int a = 0;
            for(int i=0;i<numeros.size();i++)// se saca el numero de los cuadruplos desntro del while
            {
                ///
                String b="";
                int s=  (int) numeros.elementAt(i);
                System.out.println("s"+s);
                int q=Integer.parseInt(map.get(oper2)),p=Integer.parseInt(map.get(oper1));
           try
           {
                a=Integer.parseInt(map.get(""+(s-1)));
                map.put(""+(s-1), ""+(a+1));
           }
           catch(Exception e)
           {
               b=map.get(""+(s-1));
               map.put(""+(s-1), ""+(b));
           }
            
                while(p<q) // para la salidas
                {
            if(map.get(""+(s-1))==null)
            {
                sal+= " -> : " +  res+ "\n";
                txta1.setText(sal);
                System.out.println("nullll");
            
            
            }
            else{
            
            sal+= " -> : " +  map.get(""+(s-1))+ "\n";
            txta1.setText(sal);
            try{
            a=Integer.parseInt(map.get(""+(s-1)));
            map.put(""+(s-1), ""+(a+1));
            }catch(Exception e)
            {
                b=map.get(""+(s-1)); // en caso de no sea valor numerico
           
            }
            
            } 
            
            try{int pa = Integer.parseInt(oper4);
            p=p+pa;}
            catch(Exception e){ // en caso de que no exista contador en el ciclo
                p=p+1;
                System.out.println("sin contador "); 
            }
                }
            }    
            cuadruplos(6);
            endw=false; 
            
            

            }
        if(reser==18)//For
            {
                forr=true;
            }
        if(reser==17)//endfor
            {
                cuadruplos(6);

            }
        if(reser==42)//:
            {
                cuadruplos(8);
            }
        if(reser==32)//,
            {
                com = true;
            }
        
        
        
        
        if(reser==0 || reser==43)//si es identificador
        {
            
            if (reser==43)
            {
                cons1=true;
            }
                while(!poperandoscompara.empty())
                {
                    String a=(String)poperandoscompara.pop();//INVERTIR PILA
                    poperanco2.push(a);
                }
                int busquea = poperanco2.search(token);//
                System.out.println(""+ token);
                try{
                    
                
                if(busquea>=0){// se busva en la pilas de comparacion para determinar
                                             //el tipo para el semantico
                    System.out.println("j"+busquea);
                tipo=(String) tiposcompara.elementAt(busquea-1);//-1 ya que la funcion search empieza desde 1 y no 0
                tipos.push(tipo);
                imprimepilatipos();
                poperandos.push(token);
                imprimepilaop2();
                
                if(plus==true || resta==true || multi == true || men==true || may==true || meni==true || mayi==true || difde==true || whil==true)
                {
                  if(whil==true)
                    {
                        
                        System.out.println("whil whil");
                        cuadruplos(9);
                        whil=false;
                        
                    }
                     else
                     {
                    cuadruplos(1);
                    plus=false;
                    multi=false;
                    resta=false;
                    men=false;
                    may=false;
                    mayi=false;meni=false;difde=false;
                     }
                    if(If==true)
                    {
                        cuadruplos(3);
                        If=false;
                    }
                    if(WHILE==true)
                    {
                        cuadruplos(3);
                        WHILE=false;
                    }
                    if(forr==true)
                    {
                        cuadruplos(7);
                        forr=false;
                        
                    }
                   
                   
                   
                
                }
                
                

                
                }
                else
                {
                    if(cons1==false)
                    err+= "Varible "+token+ " no definida \n";
                    else
                    cons=false;    
                    
                    tipos.push("integer");
                    
                    poperandos.push(token);
                    poperanco2.push(token);
                    poperandoscompara.push(token);
                    tiposcompara.push("integer");
                    imprimepilaop2();
                    imprimepilatipos();
                    if(plus==true || resta==true || multi == true || men==true || may==true || meni==true || mayi==true || difde==true || whil==true)
                {
                    
                     if(whil==true)
                    {
                        System.out.println("whil");
                        cuadruplos(9);
                        whil=false;
                    }
                     else
                     {
                    cuadruplos(1);
                    plus=false;
                    multi=false;
                    resta=false;
                    men=false;
                    may=false;
                    mayi=false;meni=false;difde=false;
                     }
                    if(If==true)
                    {
                        cuadruplos(3);
                        If=false;
                    }
                    if(If==true)
                    {
                        cuadruplos(3);
                        If=false;
                    }
                    
                    
                    
                }
                    

                
                }
                }catch(Exception e)
                        {
                        if(cons1==false)
                    err+= "Varible "+token+ " no definida \n";
                    else
                    cons=false;    
                    
                    tipos.push("integer");
                    
                    poperandos.push(token);
                    poperanco2.push(token);
                    poperandoscompara.push(token);
                    tiposcompara.push("integer");
                    imprimepilaop2();
                    imprimepilatipos();
                    if(plus==true || resta==true || multi == true || men==true || may==true || meni==true || mayi==true || difde==true || whil==true)
                {
                    
                     if(whil==true)
                    {
                        System.out.println("whil");
                        cuadruplos(9);
                        whil=false;
                    }
                     else
                     {
                    cuadruplos(1);
                    plus=false;
                    multi=false;
                    resta=false;
                    men=false;
                    may=false;
                    mayi=false;meni=false;difde=false;
                     }
                    if(If==true)
                    {
                        cuadruplos(3);
                        If=false;
                    }
                    if(If==true)
                    {
                        cuadruplos(3);
                        If=false;
                    }
                    
                    
                    
                }
                        }
                
            
                
        }
        if(reser==28)//+
        {
            plus=true;
            poperadores.push(token);
            imprimepilaoperadores();
            
            
        }
        if(reser==29)//-
        {
            resta=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
        if(reser==30)//*
        {
            multi=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
         if(reser==31)// /
        {
            poperadores.push(token);
            imprimepilaoperadores();
        }
          if(reser==32)// =
        {
            igual=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
          if(reser==35)// <
        {
            men=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
            if(reser==36)// >
        {
            may=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
              if(reser==37)// >=
        {
            mayi=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
                if(reser==38)// <=
        {
            meni=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
                if(reser==39)// !=
        {
            difde=true;
            poperadores.push(token);
            imprimepilaoperadores();
        }
    }
    }
    
   
}




// 6
}
void imprimepilatipos()
{
    for(int i=0;i<tipos.size();i++){
        tip+=tipos.elementAt(i)+" ";
    }
    tip+="\n";
    txttipos.setText(tip);
   
}
void imprimepilasaltos()
{
    for(int i=0;i<psaltos.size();i++){
        saltos+=psaltos.elementAt(i)+" ";
    }
    saltos+="\n";
    txtsaltos.setText(saltos);
   
}
void imprimepilatiposc()
{
    for(int i=0;i<tipos.size();i++){
        tipoq+=tipos.elementAt(i)+" ";
    }
    tipoq+="\n";
    txtsaltos.setText(tipoq);
   
}
void limpiapilatipos2()
{
    while(!tipos.empty())
    {
        tipos.pop();
    }
   
}
void imprimepilaoperadores()
{
    for(int i=0;i<poperadores.size();i++){
        operadores+=poperadores.elementAt(i)+" ";
    }
    operadores+="\n";
    txtoperadores.setText(operadores);
}
void limpiapilaoperandos()
{
   while(!poperandos.empty())
    {
        poperandos.pop();
    }
}
void imprimepilaop2()
{
    for(int i=0;i<poperandos.size();i++){
        operando+=poperandos.elementAt(i)+" ";
    }
    operando+="\n";
    txtoperandos.setText(operando);
   
}
void imprimepilaop3()
{
    for(int i=0;i<poperandoscompara.size();i++){
        operando1+=poperandoscompara.elementAt(i)+" ";
    }
    operando1+="\n";
    txtsaltos.setText("\n"+operando1);
   
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        numeros.clear();
        map.clear();
        txta1.setText("");
        sal="";
        poperanco2.clear();
        saltos="";
        err="";
        indice=1;
        num=1;
        tabla.setModel(model);
        model.setRowCount(0);
        peek="";
        txttipos.setText("");
        txtoperandos.setText("");
        txterr.setText("");
        tip="";
        operando="";
        operadores="";
        poperadores.clear();
        poperandos.clear();
        tipos.clear();
        poperandoscompara.clear();
        tiposcompara.clear();
        tipos.clear();
        psaltos.clear();
        analiza();
        txterr.setText(err);
  Iterator it = map.keySet().iterator();
  while(it.hasNext()){
  String key = (String) it.next();
  System.out.println("Clave: " + key + " -> Valor: " + map.get(key));
 

}
      /*  System.out.println(""+ nubo+ " "+ nobo1);
        for(nubo=nubo+2;nubo<nobo1-2;nubo++)
        {
            System.out.println(""+ nubo+ " "+ nobo1);
            model.removeRow(nubo);
        }
                    //model.removeRow(nubo+1);
                    //model.removeRow(nobo1-3);
        */            
          
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tabla;
    private javax.swing.JTextPane txta;
    private javax.swing.JTextPane txta1;
    private javax.swing.JTextPane txterr;
    private javax.swing.JTextArea txtoperadores;
    private javax.swing.JTextArea txtoperandos;
    private javax.swing.JTextPane txtsaltos;
    private javax.swing.JTextArea txttipos;
    // End of variables declaration//GEN-END:variables
}
